kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

workspace:
  path: /fengziren/src

steps:
# - name: fetch
#   image: alpine/git
#   commands:
#   - git fetch --tags
# 测试
- name: test
  image: golang
  volumes:
  - name: deps
    path: /go
  environment:
      GO111MODULE: "on"
      GOPROXY: "https://goproxy.cn,direct"
  commands:
  - go mod tidy
  - go test
# 构建
- name: build
  image: golang
  volumes:
  - name: golang
    path: /go
  environment:
    GO111MODULE: "on"
    GOPROXY: "https://goproxy.cn,direct"
  commands:
  - go mod tidy
  - go build
# 微信通知
- name: wechat
  image: lizheming/drone-wechat
  pull: always
  settings:
    title: >
     {% if success %}
     ✅ {{repo.owner}}/{{repo.name}} 第 {{build.number}} 次构建成功！
     {% else %}
     ❌ {{repo.owner}}/{{repo.name}} 第 {{build.number}} 次构建失败了，快来修理下吧。
     {% endif %}
    corpid: 
      from_secret: wechat_corpid
    corp_secret:
      from_secret: wechat_corp_secret
    agent_id:
      from_secret: agent_id
    to_user: "@all"
    message: >
      {% if success %}
      😊主人，{{repo.owner}}/{{repo.name}}第{{build.number}}次构建成功！
      {% else %}
      😭主人，{{repo.owner}}/{{repo.name}}第{{build.number}}次构建失败了，快来修理下吧。
      {% endif %}
  when:
    status:
    - success
    - failure

trigger:
  branch:
  - main
  event:
  - push
  status:
  - success
  - failure